### ISSUE TITLE
Add television series' you have seen or want to

### ISSUE THREAD

**Issue by sambhav2612** [sambhav2612/hacktoberfest-bingeWatcher#1]
After committing and creating a pull request, go-to ```CONTRIBUTORS.md``` file and type in your name  with GitHub account link in following format:

- Your name [(Your GitHub username)](Your GitHub Profile Link)

For example: 
```
- Sambhav Jain [(@sambhav2612)](https://github.com/sambhav2612)
```

**Comment by dnishar1** [comment]
Entourage, heard a lot of good things about that show. #2 #Hacktoberfest

**Comment by sambhav2612** [comment]
done!
